function EEGsensors = getEEGsensorsNames()

EEGsensors = {...
              'Fz','Cz','Pz','Oz','Iz',...
              'Fp1','Fp2','F3','F4','F7'...
              'F8','T7','T8','C3','C4',...
              'P3','P4','O9','O10','P7',...
              'P8','FC1','FC2','CP1','CP2',...
              'PO3','PO4','PO7','PO8','LMAST',...
              }'; 